# Generated by Django 5.1.3 on 2025-02-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Comentario'),
        ),
    ]
