# Generated by Django 5.1.3 on 2024-11-09 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('latitude', models.FloatField(verbose_name='Latitud')),
                ('longitude', models.FloatField(verbose_name='Longitud')),
                ('state', models.CharField(max_length=100, verbose_name='Provincia')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField(verbose_name='Fecha de salida')),
                ('departure_time', models.TimeField(verbose_name='Hora de salida')),
                ('destination_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips_to', to='trip.city', verbose_name='Ciudad de destino')),
                ('origin_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips_from', to='trip.city', verbose_name='Ciudad de origen')),
            ],
        ),
        migrations.CreateModel(
            name='TripParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('driver', 'Driver'), ('passenger', 'Passenger')], max_length=10, verbose_name='Rol')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_participants', to='trip.trip', verbose_name='Viaje')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_trips', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'unique_together': {('user', 'trip')},
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='participants',
            field=models.ManyToManyField(related_name='trips', through='trip.TripParticipant', to=settings.AUTH_USER_MODEL, verbose_name='Participantes'),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=7, unique=True, verbose_name='Patente')),
                ('brand', models.CharField(max_length=50, verbose_name='Marca')),
                ('model', models.CharField(max_length=50, verbose_name='Modelo')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trip.vehicle', verbose_name='Vehículo'),
        ),
    ]
