# Generated by Django 5.1.3 on 2024-11-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_state_alter_city_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='kids_allowed',
            field=models.BooleanField(default=False, verbose_name='Se permiten niños'),
        ),
        migrations.AddField(
            model_name='trip',
            name='pet_allowed',
            field=models.BooleanField(default=False, verbose_name='Se permiten mascotas'),
        ),
        migrations.AddField(
            model_name='trip',
            name='smoking_allowed',
            field=models.BooleanField(default=False, verbose_name='Se permite fumar'),
        ),
    ]
