# Generated by Django 5.1.3 on 2025-01-19 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0006_tripjoinrequest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='state',
            unique_together={('name', 'abbreviation', 'country')},
        ),
    ]
