# Generated by Django 5.1.3 on 2025-02-12 03:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0007_alter_state_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together={('license_plate', 'owner')},
        ),
    ]
