name: Test

on:
  push:
    branches:
      - main
      - actions # test on actions branch
  pull_request:
    branches:
      - main

jobs:
    run_test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.12.3'
            
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt 
            
            - name: Run tests
              env:
                SECRET_KEY: ${{ secrets.SECRET_KEY }}
                DEBUG: ${{ secrets.DEBUG }}
                DB_NAME: ${{ secrets.DB_NAME }}
                DB_USER: ${{ secrets.DB_USER }}
                DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
                DB_HOST: ${{ secrets.DB_HOST }}
                DB_PORT: ${{ secrets.DB_PORT }}
              run: |
                cd src
                python manage.py test