name: Test

on:
  push:
    branches:
      - main
      - actions # test on actions branch
  pull_request:
    branches:
      - main

jobs:
    run_test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.12.3'
            
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt 
            
            - name: Run tests
              run: python manage.py test